version: '3.1'
services:
  spring-admin-server:
    image: jmedinaks/spring-admin-server
    networks:
      - backend
    ports: 
      - "8080:8080"
  client:
    image: jmedinaks/spring-admin-client
    networks:
      - backend
    deploy:
      mode: replicated
      replicas: 5
    depends_on:
      - server
networks:
  backend:
    driver: bridge
